import sys,os,kconfiglib
ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KCONFIG=os.path.join(ROOT,"Kconfig")
CONFIG=os.path.join(ROOT,".config")
OUTPUT=os.path.join(ROOT,"generated","config","mgl_config_gen.h")
os.environ["srctree"] = ROOT

if sys.stdout.encoding!='utf-8':
    if hasattr(sys.stdout,'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8')
    else:
        import io
        sys.stdout=io.TextIOWrapper(sys.stdout.buffer,encoding='utf-8')

def menuconfig():
    os.environ["KCONFIG_CONFIG"] = CONFIG
    kconf=kconfiglib.Kconfig(KCONFIG)
    if os.path.exists(CONFIG):
        kconf.load_config(CONFIG,replace=False)
    kconf.warn=False
    from menuconfig import menuconfig
    menuconfig(kconf)
    kconf.write_config(CONFIG)
    genheader(kconf)
    print(f"已保存: {CONFIG}")

def alldefconfig():
    kconf=kconfiglib.Kconfig(KCONFIG)
    kconf.write_config(CONFIG)
    genheader(kconf)
    print(f"已保存默认设置: {CONFIG}")
def genheader(kconf=None):
    if kconf is None:
        kconf=kconfiglib.Kconfig(KCONFIG)
        if os.path.exists(CONFIG):
            kconf.load_config(CONFIG,replace=False)
    os.makedirs(os.path.dirname(OUTPUT),exist_ok=True)
    with open(OUTPUT,"w",encoding="utf-8") as f:
        f.write("// Auto-generated by kconfig.py\n")
        f.write("#ifndef MGL_CONFIG_GEN_H\n#define MGL_CONFIG_GEN_H\n\n")
        for s in kconf.unique_defined_syms:
            if s.type==kconfiglib.BOOL:
                val="1" if s.str_value=="y" else "0"
                f.write(f"#ifndef {s.name}\n#define {s.name} {val}\n#endif\n")
            elif s.type in (kconfiglib.INT,kconfiglib.HEX):
                f.write(f"#ifndef {s.name}\n#define {s.name} {s.str_value}\n#endif\n")
            elif s.type==kconfiglib.STRING:
                f.write(f"#ifndef {s.name}\n#define {s.name} {s.str_value}\n#endif\n")
        
        f.write("\n#endif\n")
    print(f"已生成头文件: {OUTPUT}")    


if __name__ == "__main__":
    cmd=sys.argv[1] if len(sys.argv) > 1 else "alldefconfig"
    {"menuconfig":menuconfig,"alldefconfig":alldefconfig,"genheader":genheader}[cmd]()
